resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'
description 'FiveLife by Cosmo.'
version "0.1.70"


server_script '@mysql-async/lib/MySQL.lua'

client_scripts {
	'lib/utils.lua',
	'client/util.lua',
	'common/mouse.lua',
	'common/ext.lua',
	'client/main.lua',
	'client/player/messaging.lua',
	'client/player/teleportation.lua',
	'client/player/register.lua',
	'client/player/playermain.lua',
	'client/player/situations.lua',
	'client/gui/phone.lua',
	'client/player/medical.lua',
	'client/menu/interactionMenu.lua',
	'client/player/lifeMain.lua',
	'client/gui/stores.lua',
	'client/menu/menu-core.lua',
	'client/menu/menu-spawn.lua',
	'client/menu/menu-bank.lua',
	'client/menu/menu-genStore.lua',
	'client/menu/menu-gunStore.lua',
	'client/menu/menu-player.lua',
	'client/menu/menu-lowClothes_m.lua',
	'client/menu/menu-lowClothes_f.lua',
	'client/menu/menu-highClothes.lua',
	'client/menu/menu-barbershop.lua',
	'client/menu/menu-cosmeticshop.lua',
	'client/menu/menu-vehicle.lua',
	'client/menu/menu-exotic.lua',
	'client/menu/menu-bike.lua',
	'client/menu/menu-garage.lua',
	'client/menu/menu-lscustoms.lua',
	'client/menu/menu-admin.lua',
	'client/menu/menu-debug.lua',
	'client/menu/menu-fuel.lua',
	'client/menu/menu-trucking.lua',
	'client/jobs/jobs-basic.lua',
	'client/jobs/jobs-heists.lua',
	'client/jobs/jobs-interact.lua',
	'client/player/point.lua',
	'client/player/kickChecks.lua',
	'client/gui/heads.lua',
	'client/world/time.lua',
	'client/player/cheat.lua',
	'client/player/emote.lua',
	'client/gui/essentials.lua',
	'client/gui/compass.lua',
	'client/gui/pld.lua',
	'client/gui/clothes.lua',
	'client/gui/skins.lua',
	'client/jobs/police.lua',
	'client/jobs/MDT.lua',
	'client/jobs/siren.lua',
	'client/jobs/helicam.lua'
}

server_scripts {
	'lib/utils.lua',
	'common/ext.lua',
	'server/permbans.lua',
	'server/main.lua',
	'server/commands/base.lua',
	'server/commands/console.lua',
	'server/commands/police.lua',
	'server/world/time.lua',
	'server/gui/stores.lua',
	'server/gui/lscustoms.lua',
	'server/jobs/police.lua',
	'server/player/register.lua',
	'server/player/login.lua',
	'server/player/lifeMain.lua',
	'server/player/kickChecks.lua',
	'server/gui/interactionMenu.lua',
	'server/player/cheat.lua',
	'server/jobs/jobs-basic.lua',
	'server/jobs/jobs-heists.lua',
	'server/jobs/jobs-interact.lua',
	'server/jobs/siren.lua'
}
